### ISSUE TITLE
Error when dein is installed via the installer

### ISSUE THREAD

**Issue by MasaYan24** [Shougo/dein-installer.vim#3]
By installing dein via the installer by the following command,
```sh
sh -c "$(wget -O- https://raw.githubusercontent.com/Shougo/dein-installer.vim/master/installer.sh)"
```
it sends me errors when a file is opened as follows.
```sh
Error detected while processing function dein#begin[1]..dein#util#_begin[40]..dein#util#_split_rtp:
line    1:
E276: Cannot use function as a method: stridx
Error detected while processing FuncUndefined Autocommands for "*":
E276: Cannot use function as a method: stridx
Error detected while processing function dein#end[1]..dein#util#_end[15]..dein#util#_split_rtp:
line    1:
E276: Cannot use function as a method: stridx
Press ENTER or type command to continue
```

The Prerequisites is satisfied and it is a clean install.

By commenting out the default init file, ~/.config/nvim/init.vim, line 15 raises the first error.

**Comment by MasaYan24** [comment]
Solved.
The neovim in ubuntu installed with apt is old version (even execute `apt update`).
By installing neovim with newer version solved the issue.

**Comment by Shougo** [comment]
OK.    I have added the version check.

dein.vim requires Vim 8.2 or neovim 0.8+.
